import { Font } from '@react-pdf/renderer';
import JetBrainsMono_Regular from "../../fonts/JetBrainsMono-Regular.ttf";
import Beyond from "../../fonts/Beyond.ttf";
import BulletInYourHead from "../../fonts/BulletInYourHead.ttf";
import D3Digitalism from "../../fonts/D3Digitalism.ttf";
import D3Digitalism_Italic from "../../fonts/D3DigitalismI.ttf";
import DiscoDuck from "../../fonts/discoduck.ttf";
import DiscoDuck_Italic from "../../fonts/discoduckital.ttf";
import DiscoDuck_Left from "../../fonts/discoduckleft.ttf";
import DiscoDuck_3d from "../../fonts/discoduck3d.ttf";
import DiscoDuck_3d_Italic from "../../fonts/discoduck3dital.ttf";
import DiscoDuck_Chrome from "../../fonts/discoduckchrome.ttf";
import DiscoDuck_Chrome_Italic from "../../fonts/discoduckchromeital.ttf";
import DiscoDuck_Condensed from "../../fonts/discoduckcond.ttf";
import DiscoDuck_Condensed_Italic from "../../fonts/discoduckcondital.ttf";
import DiscoDuck_Expanded from "../../fonts/discoduckexpand.ttf";
import DiscoDuck_Expanded_Italic from "../../fonts/discoduckexpandital.ttf";
import DiscoDuck_Gradient from "../../fonts/discoduckgrad.ttf";
import DiscoDuck_Gradient_Italic from "../../fonts/discoduckgradital.ttf";
import DiscoDuck_Halftone from "../../fonts/discoduckhalf.ttf";
import DiscoDuck_Halftone_Italic from "../../fonts/discoduckhalfital.ttf";
import DiscoDuck_Outline from "../../fonts/discoduckout.ttf";
import DiscoDuck_Outline_Italic from "../../fonts/discoduckoutital.ttf";
import DiscoDuck_Semi_Italic from "../../fonts/discoducksemital.ttf";
import DiscoDuck_Super_Italic from "../../fonts/discoducksuperital.ttf";
import Friday13th_Bonus from "../../fonts/Friday13 Bonus NFI.otf";
import Friday13th_SH from "../../fonts/Friday13SH.otf";
import Friday13th_v12 from "../../fonts/Friday13v12.ttf";
import Justice from "../../fonts/justice.ttf";
import Justice_3d from "../../fonts/justice3d.ttf";
import Justice_Academy from "../../fonts/justiceacad.ttf";
import Justice_Chrome from "../../fonts/justicechrome.ttf";
import Justice_Condensed from "../../fonts/justicecond.ttf";
import Justice_Condensed_Outline from "../../fonts/justicecondout.ttf";
import Justice_Condensed_Straight from "../../fonts/justicecondstraight.ttf";
import Justice_Expanded from "../../fonts/justiceexpand.ttf";
import Justice_Expanded_Outline from "../../fonts/justiceexpandout.ttf";
import Justice_Expanded_Straight from "../../fonts/justiceexpandstraight.ttf";
import Justice_Gradient from "../../fonts/justicegrad.ttf";
import Justice_Gradient_Outline from "../../fonts/justicegradout.ttf";
import Justice_Halftone from "../../fonts/justicehalf.ttf";
import Justice_Italic from "../../fonts/justiceital.ttf";
import Justice_Laser from "../../fonts/justicelaser.ttf";
import Justice_Italic_Left from "../../fonts/justiceleft.ttf";
import Justice_Outline from "../../fonts/justiceout.ttf";
import Justice_Outline_Italic from "../../fonts/justiceoutital.ttf";
import Justice_Semi_Italic from "../../fonts/justicesemital.ttf";
import Justice_Outline_Straight from "../../fonts/justiceoutstraight.ttf";
import Justice_Straight from "../../fonts/justicestraight.ttf";
import Wide_Wake from "../../fonts/WIDEAWAKE.ttf";
import Wide_Wake_Black from "../../fonts/WIDEAWAKEBLACK.ttf";


Font.register({ family: 'JetBrainsMono-Regular', format: "truetype", src: JetBrainsMono_Regular });
Font.register({ family: 'Beyond', format: "truetype", src: Beyond });
Font.register({ family: 'BulletInYourHead', format: "truetype", src: BulletInYourHead });
Font.register({ family: 'D3Digitalism', format: "truetype", src: D3Digitalism });
Font.register({ family: 'D3Digitalism_Italic', format: "truetype", src: D3Digitalism_Italic });
Font.register({ family: 'DiscoDuck', format: "truetype", src: DiscoDuck });
Font.register({ family: 'DiscoDuck-Italic', format: "truetype", src: DiscoDuck_Italic });
Font.register({ family: 'DiscoDuck-Left', format: "truetype", src: DiscoDuck_Left });
Font.register({ family: 'DiscoDuck-3d', format: "truetype", src: DiscoDuck_3d });
Font.register({ family: 'DiscoDuck-3d-Italic', format: "truetype", src: DiscoDuck_3d_Italic });
Font.register({ family: 'DiscoDuck-Chrome', format: "truetype", src: DiscoDuck_Chrome });
Font.register({ family: 'DiscoDuck-Chrome-Italic', format: "truetype", src: DiscoDuck_Chrome_Italic });
Font.register({ family: 'DiscoDuck-Condensed', format: "truetype", src: DiscoDuck_Condensed });
Font.register({ family: 'DiscoDuck-Condensed-Italic', format: "truetype", src: DiscoDuck_Condensed_Italic });
Font.register({ family: 'DiscoDuck-Expanded', format: "truetype", src: DiscoDuck_Expanded });
Font.register({ family: 'DiscoDuck-Expanded-Italic', format: "truetype", src: DiscoDuck_Expanded_Italic });
Font.register({ family: 'DiscoDuck-Gradient', format: "truetype", src: DiscoDuck_Gradient });
Font.register({ family: 'DiscoDuck-Gradient-Italic', format: "truetype", src: DiscoDuck_Gradient_Italic });
Font.register({ family: 'DiscoDuck-Halftone', format: "truetype", src: DiscoDuck_Halftone });
Font.register({ family: 'DiscoDuck-Halftone-Italic', format: "truetype", src: DiscoDuck_Halftone_Italic });
Font.register({ family: 'DiscoDuck-Outline', format: "truetype", src: DiscoDuck_Outline });
Font.register({ family: 'DiscoDuck-Outline-Italic', format: "truetype", src: DiscoDuck_Outline_Italic });
Font.register({ family: 'DiscoDuck-Semi-Italic', format: "truetype", src: DiscoDuck_Semi_Italic });
Font.register({ family: 'DiscoDuck-Super-Italic', format: "truetype", src: DiscoDuck_Super_Italic });
Font.register({ family: 'Friday13th-Bonus', format: "opentype", src: Friday13th_Bonus });
Font.register({ family: 'Friday13th-SH', format: "opentype", src: Friday13th_SH });
Font.register({ family: 'Friday13th-v12', format: "truetype", src: Friday13th_v12 });
Font.register({ family: 'Justice', format: "truetype", src: Justice });
Font.register({ family: 'Justice-3d', format: "truetype", src: Justice_3d });
Font.register({ family: 'Justice-Academy', format: "truetype", src: Justice_Academy });
Font.register({ family: 'Justice-Chrome', format: "truetype", src: Justice_Chrome });
Font.register({ family: 'Justice-Condensed', format: "truetype", src: Justice_Condensed });
Font.register({ family: 'Justice-Condensed-Outline', format: "truetype", src: Justice_Condensed_Outline });
Font.register({ family: 'Justice-Condensed-Straight', format: "truetype", src: Justice_Condensed_Straight });
Font.register({ family: 'Justice-Expanded', format: "truetype", src: Justice_Expanded});
Font.register({ family: 'Justice-Expanded-Outline', format: "truetype", src: Justice_Expanded_Outline });
Font.register({ family: 'Justice-Expanded-Straight', format: "truetype", src: Justice_Expanded_Straight });
Font.register({ family: 'Justice-Gradient', format: "truetype", src: Justice_Gradient });
Font.register({ family: 'Justice-Gradient-Outline', format: "truetype", src: Justice_Gradient_Outline });
Font.register({ family: 'Justice-Halftone', format: "truetype", src: Justice_Halftone });
Font.register({ family: 'Justice-Italic', format: "truetype", src: Justice_Italic });
Font.register({ family: 'Justice-Laser', format: "truetype", src: Justice_Laser });
Font.register({ family: 'Justice-Italic-Left', format: "truetype", src: Justice_Italic_Left });
Font.register({ family: 'Justice-Outline', format: "truetype", src: Justice_Outline });
Font.register({ family: 'Justice-Outline-Italic', format: "truetype", src: Justice_Outline_Italic });
Font.register({ family: 'Justice-Semi-Italic', format: "truetype", src: Justice_Semi_Italic });
Font.register({ family: 'Justice-Outline-Straight', format: "truetype", src: Justice_Outline_Straight });
Font.register({ family: 'Justice-Straight', format: "truetype", src: Justice_Straight });
Font.register({ family: 'Wide-Wake', format: "truetype", src: Wide_Wake });
Font.register({ family: 'Wide-Wake-Black', format: "truetype", src: Wide_Wake_Black });
